In [1]:
import numpy as np
import torch 

In [ ]:
def atw_kernel(ker_base, image_dtype, Cin, level=1) : # level = J 
        zeros_len = - 1 + 2**(level-1) # 2^(J-1) -1 zeros 
        ker_len = zeros_len * 4 + len(ker_base)
        kernel_1d = np.zeros((ker_len,)) 
        kernel_1d[::zeros_len+1] = ker_base/np.sum(ker_base)
        kernel_2d = np.tensordot(kernel_1d, np.transpose(kernel_1d), axes=0)  # kernel_2d = kernel_1d dot kernel_1d
        
        # convert to tensor 
        kernel_size = kernel_2d.shape[0]
        kernel_torch = torch.tensor(kernel_2d, dtype=image_dtype).unsqueeze(0).expand(Cin, 1, kernel_size, kernel_size)
        return  kernel_torch, kernel_size

In [3]:
import torch 
x = torch.randint(9,12,(1,))
x

tensor([9])

In [4]:
torch.mul(x,x)

tensor([81])

In [5]:
x * x

tensor([81])