In [30]:
!pip install -qq openpyxl

In [31]:
import pandas as pd 
FILEPATH = '../notebooks/dataset_quality_report.xlsx'
qdf_i = pd.read_excel(FILEPATH,sheet_name='interpretation' )
qdf_f = pd.read_excel(FILEPATH,sheet_name='faciesmark' )
qdf_s = pd.read_excel(FILEPATH,sheet_name='stdata12' )

In [32]:
qdf_i.columns = list(map(lambda x : x.strip(), qdf_i.columns))
qdf_f.columns = list(map(lambda x : x.strip(), qdf_f.columns))
qdf_s.columns = list(map(lambda x : x.strip(), qdf_s.columns))

## Interpretation

In [33]:
qdf_i.columns = list(map(lambda x : x.strip(), qdf_i.columns))
qdf_i.columns

Index(['Inline No.', 'No data', 'Small acquisition Gaps',
       'Large Acquisition Gaps', 'Label Misalignment', '>30% No data',
       'Random High Noise', 'Unnamed: 7'],
      dtype='object')

In [34]:
qdf_i.shape

(651, 8)

In [35]:
# no data 
qdf_i['No data'].sum() / qdf_i.shape[0] * 100

92.47311827956989

In [36]:
condition = qdf_i['No data'] == 1 
qdf_i[~condition]['Inline No.'].to_list()

[702,
 703,
 704,
 705,
 706,
 707,
 708,
 709,
 710,
 711,
 712,
 713,
 714,
 715,
 716,
 717,
 718,
 719,
 720,
 721,
 722,
 723,
 724,
 725,
 726,
 727,
 728,
 729,
 730,
 731,
 732,
 733,
 734,
 735,
 736,
 737,
 738,
 739,
 740,
 741,
 742,
 743,
 744,
 745,
 746,
 747,
 748,
 749,
 750]

In [37]:
# small acquisition gaps 
qdf_i['Small acquisition Gaps'].sum() / qdf_i.shape[0] * 100

100.0

In [38]:
qdf_i['Large Acquisition Gaps'].sum() / qdf_i.shape[0] * 100 

34.715821812596005

In [39]:
condition = qdf_i['Large Acquisition Gaps'] == 1
print(qdf_i[condition]['Inline No.'].to_list())

[100, 108, 116, 117, 118, 119, 120, 121, 122, 123, 135, 149, 150, 151, 152, 153, 154, 155, 167, 184, 186, 196, 216, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 249, 251, 252, 263, 264, 266, 276, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 304, 305, 306, 307, 308, 309, 310, 311, 312, 319, 320, 321, 322, 323, 324, 328, 329, 330, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364, 371, 392, 400, 443, 444, 465, 468, 469, 470, 471, 472, 476, 480, 488, 505, 508, 513, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539, 540, 557, 558, 559, 560, 561, 562, 563, 564, 565, 566, 567, 568, 569, 573, 575, 605, 606, 607, 608, 609, 610, 611, 612, 613, 614, 615, 652, 694, 695, 696, 697, 698, 699, 700, 701, 702, 703, 704, 705, 706, 707, 708, 709, 710, 711, 712, 713, 714, 715, 716, 717, 718, 719, 720, 721, 722, 723, 724,

In [40]:

qdf_i['>30% No data'].sum() / qdf_i.shape[0] * 100 

7.680491551459294

In [41]:

qdf_i['Label Misalignment'].sum() / qdf_i.shape[0] * 100 

7.680491551459294

In [42]:
cond = qdf_i['Label Misalignment'] == 1
print(qdf_i[cond]['Inline No.'].to_list())

[701, 702, 703, 704, 705, 706, 707, 708, 709, 710, 711, 712, 713, 714, 715, 716, 717, 718, 719, 720, 721, 722, 723, 724, 725, 726, 727, 728, 729, 730, 731, 732, 733, 734, 735, 736, 737, 738, 739, 740, 741, 742, 743, 744, 745, 746, 747, 748, 749, 750]


In [43]:
# inlines with 30% missing values 
cond_miss = qdf_i['>30% No data'] == 1
print(qdf_i[cond_miss]['Inline No.'].to_list())
print(len(qdf_i[cond_miss]['Inline No.'].to_list()))

[701, 702, 703, 704, 705, 706, 707, 708, 709, 710, 711, 712, 713, 714, 715, 716, 717, 718, 719, 720, 721, 722, 723, 724, 725, 726, 727, 728, 729, 730, 731, 732, 733, 734, 735, 736, 737, 738, 739, 740, 741, 742, 743, 744, 745, 746, 747, 748, 749, 750]
50


## Cleaning the datasets

In [2]:
# cleaning the datasets , original paths

# interpretation
INTERPRETATION_VOL_PATH = '../data/f3_interpretation/inline_vol.npy'
INTERPRETATION_LABEL_PATH = '../data/f3_interpretation/inline_label.npy'

# faciesmark dataset 
FACIESMARK_VOL_PATH = '../data/faciesmark/raw/seismic_entire_volume.npy'
FACIESMARK_LABEL_PATH = '../data/faciesmark/raw/labels_entire_volume.npy'


# stdata12 dataset 
STDATA_VOL_PATH = '../data/stdata12/stdata_12_amplitude.npy'
STDATA_LABEL_PATH = '../data/stdata12/stdata_12_labels.npy'


## cleaned dataset paths 

# interpretation
INTERPRETATION_VOL_PATH_CLEAN = '../data/clean/f3_interpretation/inline_vol.npy'
INTERPRETATION_LABEL_PATH_CLEAN = '../data/clean/f3_interpretation/inline_label.npy'

# faciesmark dataset 
FACIESMARK_VOL_PATH_CLEAN = '../data/clean/faciesmark/raw/seismic_entire_volume.npy'
FACIESMARK_LABEL_PATH_CLEAN = '../data/clean/faciesmark/raw/labels_entire_volume.npy'


# stdata12 dataset 
STDATA_VOL_PATH_CLEAN = '../data/clean/stdata12/stdata_12_amplitude.npy'
STDATA_LABEL_PATH_CLEAN = '../data/clean/stdata12/stdata_12_labels.npy'


## Interpretation 

In [45]:
'Label Misalignment'

'Label Misalignment'

In [46]:
# cleaning interpretation 
import numpy as np 
inter_vol = np.load(INTERPRETATION_VOL_PATH)
inter_labels = np.load(INTERPRETATION_LABEL_PATH)

inter_vol.shape, inter_labels.shape

((651, 951, 462), (651, 951, 462))

In [47]:
# removing the first 100 twt samples 
inter_vol_twt = inter_vol[:,:,101:]
print(inter_vol_twt.shape)

inter_labels_twt = inter_labels[:,:,101:]
print(inter_labels_twt.shape)

(651, 951, 361)
(651, 951, 361)


In [48]:
# removing inlines with > 30% '0' 
# last 50 inlines 
inter_vol_miss = inter_vol_twt[:601,:,:]
inter_labels_miss = inter_labels_twt[:601,:,:]

inter_vol_miss.shape, inter_labels_miss.shape


((601, 951, 361), (601, 951, 361))

In [49]:
# write to numpy  
np.save(INTERPRETATION_VOL_PATH_CLEAN, inter_vol_miss)
np.save(INTERPRETATION_LABEL_PATH_CLEAN , inter_labels_miss)

In [50]:
np.unique(inter_labels_miss)

array([2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8)

## Faciesmark

In [4]:
## faciesmark 
import numpy as np

facies_vol = np.load(FACIESMARK_VOL_PATH)
facies_label  = np.load(FACIESMARK_LABEL_PATH)

facies_vol.shape, facies_label.shape

((599, 901, 255), (599, 901, 255))

In [5]:
# removing the last two inlines containing random high noise 
facies_vol_clean = facies_vol[:-2, :, : ]
facies_label_clean = facies_label[:-2 , : , : ]

facies_vol_clean.shape, facies_label_clean.shape

((597, 901, 255), (597, 901, 255))

In [6]:
# write to clean path 
np.save(FACIESMARK_VOL_PATH_CLEAN, facies_vol_clean)
np.save(FACIESMARK_LABEL_PATH_CLEAN, facies_label_clean)

In [7]:
# labels 
np.unique(facies_label_clean)

array([0, 1, 2, 3, 4, 5], dtype=uint8)

## stdata-12

In [8]:
stdata_vol = np.load(STDATA_VOL_PATH)
stdata_label = np.load(STDATA_LABEL_PATH)

stdata_label.shape, stdata_vol.shape

FileNotFoundError: [Errno 2] No such file or directory: '../data/stdata12/stdata_12_amplitude.npy'

In [ ]:
# removing the first 100 twt 
stdata_vol_twt = stdata_vol[:,:,101:]
stdata_label_twt  = stdata_label[:,:,101:]

stdata_vol_twt.shape, stdata_label_twt.shape

((4, 951, 362), (4, 951, 362))

In [ ]:
np.unique(stdata_label_twt)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
      dtype=float32)

In [ ]:
# write to clean paths 
np.save(STDATA_VOL_PATH_CLEAN, stdata_vol_twt)
np.save(STDATA_LABEL_PATH_CLEAN, stdata_label_twt)